core/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('django.contrib.auth.urls')),
    path('', include('posts.urls')),
    path('panel/', include('accounts.urls')),
]



if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path,include
from . import views


app_name = "posts"
urlpatterns = [

    # Class views urls
    path('',views.PostListView.as_view(),name="home"),
    path('<int:page>/',views.PostListView.as_view(),name = "home"),
    path('posts/<slug>',views.PostDetail.as_view(),name = "post"),
    path('Authors/<slug:phoneNumber>',views.AuthorDetail.as_view(),name = "author"),
    path('Authors/<slug:phoneNumber>/<int:page>',views.AuthorDetail.as_view(),name = "author"),
    path('Category/<slug>',views.CategoryDetail.as_view(),name = "category"),
    path('Category/<slug>/<int:page>',views.CategoryDetail.as_view(),name = "category"),
    path('aboutUs/',views.aboutUsPage,name="aboutUs")
]

posts/models.py
from django.db import models
from core.settings import AUTH_USER_MODEL as User
from .managers import *
from django.urls import reverse
from django.utils import timezone
from utils.utils import jalali_converter
from django.utils.html import format_html



class Category(models.Model):
    status_ch = (
        ('a' , "Active"),
        ('d', "Deactive"),
    )
    title = models.CharField(max_length=50,verbose_name="تیتر")
    slug = models.SlugField(max_length=40, unique = True,verbose_name="آدرس")
    Cover = models.ImageField(upload_to="images",null=True,blank=True,verbose_name="تصویر")
    status = models.CharField(max_length=1,choices = status_ch,verbose_name="وضعیت")

    objects = CategoryManager()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "دسته بندی"
        verbose_name_plural = "دسته بندی ها"






class Post(models.Model):
    status_ch = (
        ('p' , "انتشار یافته"),
        ('d', "پیش نویس"),
        ('i', "در انتظار انتشار"),
        ('b',"برگشت داده شده"),
    )



    title = models.CharField(max_length=50,verbose_name="تیتر")
    text = models.TextField(verbose_name="متن")
    Author = models.ForeignKey(User,on_delete=models.CASCADE,related_name="posts",verbose_name="نویسنده")
    Cover = models.ImageField(upload_to="images",null=True,blank=True,verbose_name="تصویر")
    drafted = models.DateTimeField(auto_now_add=True,verbose_name="تاریخ پیش نویس")
    publish = models.DateTimeField(default=timezone.now,verbose_name="تاریخ انتشار")
    update = models.DateTimeField(auto_now=True,verbose_name="تاریخ آپدیت")
    slug = models.SlugField(max_length=40, unique = True,verbose_name="آدرس")
    status = models.CharField(max_length=1,choices = status_ch,verbose_name="وضعیت")
    Category = models.ManyToManyField(Category,related_name = "posts",verbose_name="دسته بندی")


    class Meta:
        verbose_name = "پست"
        verbose_name_plural = "پست ها"

    def preview(self):
        txtperview = self.text[:123] + " .... "
        return txtperview


    # def get_absolute_url(self):
    #     return reverse("account:home")


    def jpublish(self):
        return jalali_converter(self.publish)
    jpublish.short_description = "publish"

    def __str__(self):
        return self.title

    def Cover_tags(self):
        return format_html("<img width=120 style='border-radius:5px' src='{}'>".format(self.Cover.url))

    objects = PostManager()

posts/views.py
from django.shortcuts import render,get_object_or_404
from django.http import JsonResponse
from . import models
from django.core.paginator import Paginator
from django.utils import timezone
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from accounts.models import User


#----------------------------------------------------------------------------------------------
class PostListView(ListView):
    model = models.Post
    context_object_name = "Posts"
    template_name = "posts/classBaseViews/home.html"
    queryset = models.Post.objects.published()[::-1]
    paginate_by = 5
#----------------------------------------------------------------------------------------------
class PostDetail(DetailView):
    template_name = "posts/classBaseViews/Post_detail.html"
    def get_object(self):
        slug = self.kwargs.get('slug')
        return get_object_or_404(models.Post.objects.published(), slug=slug)
#----------------------------------------------------------------------------------------------
class AuthorDetail(ListView):
    paginate_by = 3
    template_name = "posts/classBaseViews/Author_detail.html"

    def get_queryset(self):
        global Author
        phoneNumber = self.kwargs.get('phoneNumber')
        Author = User.objects.get(phoneNumber=phoneNumber)
        return Author.posts.published()[::-1]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['Author'] = Author
        return context
#----------------------------------------------------------------------------------------------
class CategoryDetail(ListView):
    paginate_by = 4
    template_name = "posts/classBaseViews/Category_detail.html"

    def get_queryset(self):
        global Category
        slug = self.kwargs.get('slug')
        Category = get_object_or_404(models.Category.objects.actived(), slug=slug)
        return Category.posts.published()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['Category'] = Category
        return context
#----------------------------------------------------------------------------------------------
def aboutUsPage(request):
    return render(request,'posts/classBaseViews/aboutUs.html')

posts/templates/posts/classBaseViews/Author_detail.html
{% extends "posts/base.html" %}
{% load static %}


{% block img %}{{Author.Avatar.url}}{% endblock %}

{% block title %}{{Author}}{% endblock %}
{% block sub-title %}نویسنده{% endblock %}


{% block content %}
<div class="container px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
          <div class="col-md-10 col-lg-8 col-xl-7">
              <!-- Post preview-->
            {%  for post in object_list %}
              <div class="post-preview">
                  <a href="{% url 'posts:post' post.slug %}">
                      <h2 class="post-title">{{post.title}}</h2>
                      <h3 class="post-subtitle">{{post.preview|safe}}</h3>
                  </a>
                  <p class="post-meta">
                      نوشته شده در تاریخ
                      {{post.jpublish}}
                  </p>
              </div>
            {% endfor %}
            <div class="clearfix pager-botton">
              {% if page_obj.has_next %}
                  <a class="btn btn-primary float-right " href="{% url 'posts:author' Author.phoneNumber page_obj.next_page_number %}">پست قدیمی &rarr;</a>
              {% endif %}
              {% if page_obj.has_previous %}
                  <a class="btn btn-primary float-right " href="{% url 'posts:author' Author.phoneNumber page_obj.previous_page_number %}">پست جدید &larr;</a>
              {% endif %}
            </div>

{% endblock %}

posts/templates/posts/classBaseViews/Category_detail.html
{% extends "posts/base.html" %}
{% load static %}
{% load base_tags %}

{% block img %}{{Category.Cover.url}}{% endblock %}
{% block navbar %}{% home_navbar %}{% endblock %}
{% block title %}{{Category.title}}{% endblock %}
{% block sub-title %}none{% endblock %}


{% block content %}
<div class="container px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
          <div class="col-md-10 col-lg-8 col-xl-7">
              <!-- Post preview-->
            {%  for post in object_list %}
              <div class="post-preview" >
                  <a href="{% url 'posts:post' post.slug %}">
                      <h2 class="post-title">{{post.title}}</h2>
                      <h3 class="post-subtitle">{{post.preview|safe}}</h3>
                  </a>
                  <p class="post-meta">
                      نوشته شده در تاریخ
                      {{post.jpublish}}
                  </p>
              </div>
            {% endfor %}
            <div class="clearfix pager-botton">
              {% if page_obj.has_next %}
                  <a class="btn btn-primary float-right " href="{% url 'posts:category' Category.slug page_obj.next_page_number %}">پست قدیمی &rarr;</a>
              {% endif %}
              {% if page_obj.has_previous %}
                  <a class="btn btn-primary float-right " href="{% url 'posts:category' Category.slug page_obj.previous_page_number %}">پست جدید &larr;</a>
              {% endif %}
            </div>
{% endblock %}

posts/templates/posts/classBaseViews/Post_detail.html
{% extends "posts/base.html" %}
{% load static %}
{% block img %}{{post.Cover.url}}{% endblock %}
{% block title %}{{object.title}}{% endblock %}

{% block sub-title %}{{post.Author}}{% endblock %}


{% block content %}
<div class="container px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
          <div class="col-md-10 col-lg-8 col-xl-7">
              <!-- Post preview-->
              <div class="post-preview">
                  <a>
                      <h2 class="post-title" >{{object.name}}</h2>
                      <h3 class="post-subtitle">{{object.text|safe}}</h3>
                  </a>
                  <p class="post-meta">
                    <p class="post-meta">
                       نوشته شده در تاریخ
                        {{post.jpublish}}
                  </p>
              </div>

{% endblock %}

posts/templates/posts/classBaseViews/aboutUs.html
{% extends "posts/base.html" %}
{% load static %}
{% load base_tags %}

{% block navbar %}{% Category_navbar %}{% endblock %}
{% block title %}Weblog{% endblock %}
{% block img %}{% static 'posts/images/myhome.jpg' %}{% endblock %}

{% block content %}

<div class="container px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
          <div class="col-md-10 col-lg-8 col-xl-7">
              <div class="post-preview">
                  <a >
                      <h2 class="post-title" style="text-align:center">About us</h2>
                      <br>
                      <h3 class="post-subtitle">
ورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد، در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.

                      </h3>
                  </a>
                    <br>  <br>
              </div>


{% endblock %}

posts/templates/posts/classBaseViews/home.html
{% extends "posts/base.html" %}
{% load static %}
{% load base_tags %}

{% block navbar %}{% Category_navbar %}{% endblock %}
{% block title %}Weblog{% endblock %}
{% block img %}{% static 'posts/images/yoy.jpg' %}{% endblock %}

{% block content %}

<div class="container px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
          <div class="col-md-10 col-lg-8 col-xl-7">
              <!-- Post preview-->
            {%  for post in object_list %}
              <div class="post-preview">

                  <a href="{% url 'posts:post' post.slug %} ">
                      <h2 class="post-title " >{{post.title}}</h2>
                      <h3 class="post-subtitle">{{post.preview|safe}}</h3>
                  </a>
                  <p class="post-meta">نوشته شده توسط
                      <a href="{% url 'posts:author' post.Author.pk %}">{{post.Author}}</a>
                     در تاریخ {{post.jpublish}}</p>
              </div>
            {% endfor %}

          <div class="clearfix pager-botton">
            {% if page_obj.has_next %}
                <a class="btn btn-primary float-right " href="{% url 'posts:home' page_obj.next_page_number %}">پست قدیمی &rarr;</a>
            {% endif %}
            {% if page_obj.has_previous %}
                <a class="btn btn-primary float-right " href="{% url 'posts:home' page_obj.previous_page_number %}">پست جدید &larr;</a>
            {% endif %}
        </div>
{% endblock %}