accounts/urls.py
from django.contrib.auth import views as viewsD
from django.urls import path
from . import views as viewsA


app_name= 'account'


urlpatterns = [
    path('', viewsA.PostList.as_view() ,name='panelHome'),
    path('Post/create/', viewsA.PostCreate.as_view() ,name='create'),
    path('Post/preview/<int:pk>', viewsA.PostPreview.as_view() ,name='preview'),
    path('Post/update/<int:pk>', viewsA.PostUpdate.as_view() ,name='update'),
    path('Category/create/', viewsA.CategoryCreate.as_view() ,name='create-category'),
    path('Post/delete/<int:pk>', viewsA.PostDelete.as_view() ,name='delete'),
    path('profile/', viewsA.Profile.as_view() ,name='profile'),
    path('Users/AuthorToUser/<int:pk>',viewsA.AuthorToUser.as_view(),name='AuthorToUser'),
    path('Users/situation/<int:pk>',viewsA.Situation.as_view(),name='situation'),
    path('Users/',viewsA.UserList.as_view(),name='userlist'),
    path('Post/Publish/<int:pk>', viewsA.PostPublish.as_view() ,name='publish'),
    path('َUsers/PasswordChangeView',viewsA.PasswordChangeView.as_view(),name='PasswordChangeView')

]

core/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('django.contrib.auth.urls')),
    path('', include('posts.urls')),
    path('panel/', include('accounts.urls')),
]



if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path,include
from . import views


app_name = "posts"
urlpatterns = [

    # Class views urls
    path('',views.PostListView.as_view(),name="home"),
    path('<int:page>/',views.PostListView.as_view(),name = "home"),
    path('posts/<slug>',views.PostDetail.as_view(),name = "post"),
    path('Authors/<slug:phoneNumber>',views.AuthorDetail.as_view(),name = "author"),
    path('Authors/<slug:phoneNumber>/<int:page>',views.AuthorDetail.as_view(),name = "author"),
    path('Category/<slug>',views.CategoryDetail.as_view(),name = "category"),
    path('Category/<slug>/<int:page>',views.CategoryDetail.as_view(),name = "category"),
    path('aboutUs/',views.aboutUsPage,name="aboutUs")
]

posts/models.py
from django.db import models
from core.settings import AUTH_USER_MODEL as User
from .managers import *
from django.urls import reverse
from django.utils import timezone
from utils.utils import jalali_converter
from django.utils.html import format_html



class Category(models.Model):
    status_ch = (
        ('a' , "Active"),
        ('d', "Deactive"),
    )
    title = models.CharField(max_length=50,verbose_name="تیتر")
    slug = models.SlugField(max_length=40, unique = True,verbose_name="آدرس")
    Cover = models.ImageField(upload_to="images",null=True,blank=True,verbose_name="تصویر")
    status = models.CharField(max_length=1,choices = status_ch,verbose_name="وضعیت")

    objects = CategoryManager()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "دسته بندی"
        verbose_name_plural = "دسته بندی ها"






class Post(models.Model):
    status_ch = (
        ('p' , "انتشار یافته"),
        ('d', "پیش نویس"),
        ('i', "در انتظار انتشار"),
        ('b',"برگشت داده شده"),
    )



    title = models.CharField(max_length=50,verbose_name="تیتر")
    text = models.TextField(verbose_name="متن")
    Author = models.ForeignKey(User,on_delete=models.CASCADE,related_name="posts",verbose_name="نویسنده")
    Cover = models.ImageField(upload_to="images",null=True,blank=True,verbose_name="تصویر")
    drafted = models.DateTimeField(auto_now_add=True,verbose_name="تاریخ پیش نویس")
    publish = models.DateTimeField(default=timezone.now,verbose_name="تاریخ انتشار")
    update = models.DateTimeField(auto_now=True,verbose_name="تاریخ آپدیت")
    slug = models.SlugField(max_length=40, unique = True,verbose_name="آدرس")
    status = models.CharField(max_length=1,choices = status_ch,verbose_name="وضعیت")
    Category = models.ManyToManyField(Category,related_name = "posts",verbose_name="دسته بندی")


    class Meta:
        verbose_name = "پست"
        verbose_name_plural = "پست ها"

    def preview(self):
        txtperview = self.text[:123] + " .... "
        return txtperview


    # def get_absolute_url(self):
    #     return reverse("account:home")


    def jpublish(self):
        return jalali_converter(self.publish)
    jpublish.short_description = "publish"

    def __str__(self):
        return self.title

    def Cover_tags(self):
        return format_html("<img width=120 style='border-radius:5px' src='{}'>".format(self.Cover.url))

    objects = PostManager()

posts/views.py
from django.shortcuts import render,get_object_or_404
from django.http import JsonResponse
from . import models
from django.core.paginator import Paginator
from django.utils import timezone
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from accounts.models import User


#----------------------------------------------------------------------------------------------
class PostListView(ListView):
    model = models.Post
    context_object_name = "Posts"
    template_name = "posts/classBaseViews/home.html"
    queryset = models.Post.objects.published()[::-1]
    paginate_by = 5
#----------------------------------------------------------------------------------------------
class PostDetail(DetailView):
    template_name = "posts/classBaseViews/Post_detail.html"
    def get_object(self):
        slug = self.kwargs.get('slug')
        return get_object_or_404(models.Post.objects.published(), slug=slug)
#----------------------------------------------------------------------------------------------
class AuthorDetail(ListView):
    paginate_by = 3
    template_name = "posts/classBaseViews/Author_detail.html"

    def get_queryset(self):
        global Author
        phoneNumber = self.kwargs.get('phoneNumber')
        Author = User.objects.get(phoneNumber=phoneNumber)
        return Author.posts.published()[::-1]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['Author'] = Author
        return context
#----------------------------------------------------------------------------------------------
class CategoryDetail(ListView):
    paginate_by = 4
    template_name = "posts/classBaseViews/Category_detail.html"

    def get_queryset(self):
        global Category
        slug = self.kwargs.get('slug')
        Category = get_object_or_404(models.Category.objects.actived(), slug=slug)
        return Category.posts.published()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['Category'] = Category
        return context
#----------------------------------------------------------------------------------------------
def aboutUsPage(request):
    return render(request,'posts/classBaseViews/aboutUs.html')

posts/templates/posts/partials/home_navbar.html
<div class="collapse navbar-collapse" id="navbarResponsive">
    <ul class="navbar-nav ms-auto py-4 py-lg-0">
          <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'posts:home' %}">home</a></li>
    </ul>
</div>

posts/templates/posts/partials/navbar_category.html
<div class="collapse navbar-collapse" id="navbarResponsive">
    <ul class="navbar-nav ms-auto py-4 py-lg-0">
      {% for cat in cats %}
          <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'posts:category' cat.slug %}">{{cat.title}}</a></li>
        {% endfor %}
        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'account:panelHome' %}">پنل</a></li>
    </ul>
</div>

posts/templates/posts/partials/navbar_home.html
<!-- <div class="collapse navbar-collapse" id="navbarResponsive">
    <ul class="navbar-nav ms-auto py-4 py-lg-0">
      {% for ban in band %}
          <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="Songer/{{ban.slug}}">{{ban.name}}</a></li>
        {% endfor %}
    </ul>
</div> -->



<nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
    <div class="container px-4 px-lg-5">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto py-4 py-lg-0">
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'old:home' %}">Home</a></li>
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'account:home' %}">Login</a></li>
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'old:about' %}">Songs</a></li>
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'old:about' %}">Songers</a></li>
                <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'old:about' %}">Bands</a></li>
            </ul>
        </div>
    </div>
</nav>

posts/templates/posts/partials/panel.html
{% load admin_urls %}
<div class="collapse navbar-collapse" id="navbarResponsive">
    <ul class="navbar-nav ms-auto py-4 py-lg-0">
          <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="#">panel</a></li>
    </ul>
</div>