accounts/urls.py
from django.contrib.auth import views as viewsD
from django.urls import path
from . import views as viewsA


app_name= 'account'


urlpatterns = [
    path('', viewsA.PostList.as_view() ,name='panelHome'),
    path('Post/create/', viewsA.PostCreate.as_view() ,name='create'),
    path('Post/preview/<int:pk>', viewsA.PostPreview.as_view() ,name='preview'),
    path('Post/update/<int:pk>', viewsA.PostUpdate.as_view() ,name='update'),
    path('Category/create/', viewsA.CategoryCreate.as_view() ,name='create-category'),
    path('Post/delete/<int:pk>', viewsA.PostDelete.as_view() ,name='delete'),
    path('profile/', viewsA.Profile.as_view() ,name='profile'),
    path('Users/AuthorToUser/<int:pk>',viewsA.AuthorToUser.as_view(),name='AuthorToUser'),
    path('Users/situation/<int:pk>',viewsA.Situation.as_view(),name='situation'),
    path('Users/',viewsA.UserList.as_view(),name='userlist'),
    path('Post/Publish/<int:pk>', viewsA.PostPublish.as_view() ,name='publish'),
    path('َUsers/PasswordChangeView',viewsA.PasswordChangeView.as_view(),name='PasswordChangeView')

]

core/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('django.contrib.auth.urls')),
    path('', include('posts.urls')),
    path('panel/', include('accounts.urls')),
]



if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, AbstractUser
from .managers import *
from django.utils import timezone
# ----------------------------------------------------------------------------------------------------------------------------
class User(AbstractBaseUser):
    phoneNumber = models.CharField(unique=True, max_length=11)
    firstName = models.CharField(max_length=100, null=True, blank=True)
    lastName = models.CharField(max_length=100, null=True, blank=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    special_user = models.DateTimeField(default=timezone.now, verbose_name="کاربر ویژه تا")
    Avatar = models.ImageField(upload_to="images/Avatar",blank=True,null=True)
    is_author = models.BooleanField(default = False, verbose_name = "وضعیت نویسندگی")

    code = models.IntegerField(blank=True,null=True)


    USERNAME_FIELD = 'phoneNumber'
    objects = MyUserManager()

    def __str__(self):
        return str(self.firstName) + " " + str(self.lastName)

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    def is_staff(self):
        return self.is_admin

    def name(self):
        return str(self.firstName) + " " + str(self.lastName)

    def is_special_user(self):
        if self.special_user > timezone.now():
            return True
        else:
            return False

    is_special_user.boolean = True
    is_special_user.short_description = "وضعیت کاربر ویژه"

posts/models.py
from django.db import models
from core.settings import AUTH_USER_MODEL as User
from .managers import *
from django.urls import reverse
from django.utils import timezone
from utils.utils import jalali_converter
from django.utils.html import format_html



class Category(models.Model):
    status_ch = (
        ('a' , "Active"),
        ('d', "Deactive"),
    )
    title = models.CharField(max_length=50,verbose_name="تیتر")
    slug = models.SlugField(max_length=40, unique = True,verbose_name="آدرس")
    Cover = models.ImageField(upload_to="images",null=True,blank=True,verbose_name="تصویر")
    status = models.CharField(max_length=1,choices = status_ch,verbose_name="وضعیت")

    objects = CategoryManager()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "دسته بندی"
        verbose_name_plural = "دسته بندی ها"






class Post(models.Model):
    status_ch = (
        ('p' , "انتشار یافته"),
        ('d', "پیش نویس"),
        ('i', "در انتظار انتشار"),
        ('b',"برگشت داده شده"),
    )



    title = models.CharField(max_length=50,verbose_name="تیتر")
    text = models.TextField(verbose_name="متن")
    Author = models.ForeignKey(User,on_delete=models.CASCADE,related_name="posts",verbose_name="نویسنده")
    Cover = models.ImageField(upload_to="images",null=True,blank=True,verbose_name="تصویر")
    drafted = models.DateTimeField(auto_now_add=True,verbose_name="تاریخ پیش نویس")
    publish = models.DateTimeField(default=timezone.now,verbose_name="تاریخ انتشار")
    update = models.DateTimeField(auto_now=True,verbose_name="تاریخ آپدیت")
    slug = models.SlugField(max_length=40, unique = True,verbose_name="آدرس")
    status = models.CharField(max_length=1,choices = status_ch,verbose_name="وضعیت")
    Category = models.ManyToManyField(Category,related_name = "posts",verbose_name="دسته بندی")


    class Meta:
        verbose_name = "پست"
        verbose_name_plural = "پست ها"

    def preview(self):
        txtperview = self.text[:123] + " .... "
        return txtperview


    # def get_absolute_url(self):
    #     return reverse("account:home")


    def jpublish(self):
        return jalali_converter(self.publish)
    jpublish.short_description = "publish"

    def __str__(self):
        return self.title

    def Cover_tags(self):
        return format_html("<img width=120 style='border-radius:5px' src='{}'>".format(self.Cover.url))

    objects = PostManager()

accounts/forms.py
from django import forms
from .models import User
from posts.models import Post
from django.contrib.auth.forms import UserCreationForm


class ProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['phoneNumber','firstName','lastName','is_active','special_user','is_author']


    def __init__(self, *arg,**kwargs):
        user = kwargs.pop('user')

        super(ProfileForm, self).__init__( *arg,**kwargs)
        if not user.is_staff:
            self.fields['phoneNumber'].disabled = True
            self.fields['phoneNumber'].help_text = False
            self.fields['is_active'].disabled = True
            self.fields['special_user'].disabled = True
            self.fields['is_author'].disabled = True




class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200)
    class Meta:
        model = User
        fields = ('phoneNumber', 'email', 'password1', 'password2')

accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from . import forms
from django.contrib.auth.views import LoginView
from django.views.generic import (
            ListView,
            CreateView,
            UpdateView,
            DeleteView,
            DetailView,)
from accounts.models import User
from posts import models
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView
from . import mixins

 # mixins.FormValidMixin,
#----------------------------------------------------------------------------------------------
class PostList(mixins.AuthorsAccessMixin,ListView):
    template_name = "accounts/adminlte/home.html"
    def get_queryset(self):
        if self.request.user.is_staff:
            return models.Post.objects.all()[::-1]
        else:
            return models.Post.objects.filter(Author=self.request.user)
#----------------------------------------------------------------------------------------------
class PostPreview(mixins.AuthorAccessMixin,DetailView):
    template_name = "posts/classBaseViews/Post_detail.html"
    def get_object(self):
        pk = self.kwargs.get('pk')
        return get_object_or_404(models.Post, pk=pk)
#----------------------------------------------------------------------------------------------
class PostUpdate(mixins.AuthorAccessMixin, mixins.FormValidMixin, mixins.FieldsMixin, UpdateView):
    template_name = "accounts/PostCrud/Post_create_update.html"
    model = models.Post
#----------------------------------------------------------------------------------------------
class PostDelete(mixins.SuperUserAccessMixin, mixins.FormValidMixin,DeleteView):
    template_name = "accounts/PostCrud/Post_delete.html"
    model = models.Post
    success_url = reverse_lazy('account:panelHome')
#----------------------------------------------------------------------------------------------
class PostCreate(mixins.FormValidMixin, mixins.FieldsMixin,mixins.AuthorsAccessMixin, CreateView):
    template_name = "accounts/PostCrud/Post_create_update.html"
    model = models.Post
    success_url = reverse_lazy('account:panelHome')

#----------------------------------------------------------------------------------------------
class Login(LoginView):
    def get_success_url(self):
        user = self.request.user

        if user.is_staff or user.is_author:
            return reverse_lazy('account:panelHome')
        else:
            return reverse_lazy('account:profile')
#----------------------------------------------------------------------------------------------
class CategoryCreate(mixins.AuthorsAccessMixin,mixins.FormValidCategoryMixin, CreateView):
    fields = ['title','Cover','slug','status']
    template_name = "accounts/PostCrud/Category_create_update.html"
    model = models.Category
    success_url = reverse_lazy('account:panelHome')
#----------------------------------------------------------------------------------------------
class Profile(LoginRequiredMixin, UpdateView):
    form_class = forms.ProfileForm
    template_name = "accounts/Profile.html"
    model = User
    success_url = reverse_lazy('account:panelHome')

    def get_object(self):
        return User.objects.get(pk=self.request.user.pk)

    def get_form_kwargs(self):
        kwargs = super(Profile, self).get_form_kwargs()
        kwargs.update({
            'user' : self.request.user
        })
        return kwargs
#----------------------------------------------------------------------------------------------
class PasswordChangeView(PasswordChangeView):
    success_url = reverse_lazy('account:password_change_done')
#----------------------------------------------------------------------------------------------
@login_required
def loginview(request):
    return render(request,'accounts/loginview.html')
#----------------------------------------------------------------------------------------------
class PostPublish(mixins.SuperUserAccessMixin, mixins.Form2ValidMixin,UpdateView):
    template_name = "accounts/PostCrud/Post_Publish.html"
    fields = ['status']
    model = models.Post
    success_url = reverse_lazy('account:panelHome')
#----------------------------------------------------------------------------------------------
class UserList(mixins.SuperUserAccessMixin,ListView):
    template_name = "accounts/User_list/User_list.html"
    def get_queryset(self):
        return User.objects.all()
#----------------------------------------------------------------------------------------------
class AuthorToUser(mixins.SuperUserAccessMixin, mixins.Form2ValidMixin,UpdateView):
    template_name = "accounts/User_list/User_situation.html"
    model = User
    fields = ['is_author']
    success_url = reverse_lazy('account:userlist')
#----------------------------------------------------------------------------------------------
class Situation(mixins.SuperUserAccessMixin,mixins.FieldsUserSituationMixin,mixins.Form3ValidMixin,UpdateView):
    template_name = "accounts/User_list/User_situation2.html"
    model = User
    success_url = reverse_lazy('account:userlist')
#----------------------------------------------------------------------------------------------

accounts/templates/accounts/PostCrud/Category_create_update.html
{% extends 'accounts/adminlte/base.html' %}

{% load crispy_forms_tags %}

{% block titlemeta %}{% block title %}
  افزودن دسته بندی
{% endblock %}{% endblock %}
{% block main %}
<div class="col-md-12">
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title mb-0 float-left">افزودن مقاله</h3>
            </div>
            <div class="card-body">
              <form  method="post" enctype="multipart/form-data"> {% csrf_token %}
                <div class="row">
                  <div class="col-6">
                {{form.title|as_crispy_field}}
                </div>
                  <div class="col-6">
                {{form.slug|as_crispy_field}}
                </div>
                  <div class="col-6">
                {{form.Cover|as_crispy_field}}
                </div>
                    <div class="col-6">
                  {{form.status|as_crispy_field}}
                  </div>
                </div>
                    <button class="btn btn-success">ثبت مقاله</button>
              </form>

            </div>
</div>
{% endblock %}

accounts/templates/accounts/PostCrud/Post_Publish.html
{% extends 'accounts/adminlte/base.html' %}

{% load crispy_forms_tags %}

{% block titlemeta %}{% block title %}
  انتشار پست
{% endblock %}{% endblock %}
{% block main %}
<div class="col-md-8 text-center mx-auto">
          <div class="card card-danger">
            <div class="card-header" style="background-color: #0031a0;">
              <h3 class="card-title mb-0 float-left" >انتشار پست</h3>
            </div>
            <div class="card-body py-4">
              <form  method="post" > {% csrf_token %}
                <div class="row">
                      <div class="col-6">
                        {{form.status|as_crispy_field}}
                      </div>
                      </div>
                  <input type="submit" name="" value="تغییر وضعیت" class="btn btn-danger" style="background-color: #0031a0;">
              </form>
            </div>
</div>
{% endblock %}

accounts/templates/accounts/PostCrud/Post_create_update.html
{% extends 'accounts/adminlte/base.html' %}

{% load crispy_forms_tags %}

{% block titlemeta %}{% block title %}
  افزودن آهنگ
{% endblock %}{% endblock %}
{% block main %}
<div class="col-md-12">
          <!-- general form elements -->
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title mb-0 float-left">افزودن پست</h3>
            </div>
            <div class="card-body">
              <form  method="post" enctype="multipart/form-data"> {% csrf_token %}
                <div class="row">
                  <div class="col-6">
                {{form.title|as_crispy_field}}
                </div>
                  <div class="col-12">
                {{form.text|as_crispy_field}}
                </div>
                  <div class="col-6">
                {{form.slug|as_crispy_field}}
                </div>
                    <div class="col-6">
                  {{form.Cover|as_crispy_field}}
                  </div>
                    <div class="col-6">
                  {{form.Category|as_crispy_field}}
                  </div>
                  {% if user.is_staff %}
                      <div class="col-6">
                        {{form.status|as_crispy_field}}
                      </div>
                      <div class="col-6">
                    {{form.Author|as_crispy_field}}
                    </div>
                  {% else %}
                    <div class="col-6">
                      <div id="div_id_status" class="form-group">
                      <label for="id_status" class=" requiredField">
                      وضعیت<span class="asteriskField">*</span>
                      </label>
                      <div class="">
                         <select name="status" class="select form-control" required="" id="id_status">
                            <option value="" selected="">---------</option>
                            <option value="d">پیش نویس</option>
                            <option value="i">ارسال برای ادمین</option>
                         </select>
                      </div>
                      </div>
                      </div>
                      {% endif %}


                            <button class="btn btn-success">ارسال مقاله</button>
                          {% if user.is_staff and request.resolver_match.kwargs.pk %}
                              <a href="{% url 'account:delete' post.pk %}" class="btn btn-danger">حذف</a>
                          {% endif %}
              </form>

            </div>
</div>
{% endblock %}

accounts/templates/accounts/PostCrud/Post_delete.html
{% extends 'accounts/adminlte/base.html' %}

{% load crispy_forms_tags %}

{% block titlemeta %}{% block title %}
  حذف مقاله
{% endblock %}{% endblock %}
{% block main %}
<div class="col-md-8 text-center mx-auto">
          <div class="card card-danger">
            <div class="card-header">
              <h3 class="card-title mb-0 float-left">حذف مقاله</h3>
            </div>
            <div class="card-body py-4">
              <form method="post"> {% csrf_token %}
                  <p class="py-2">آیا از حذف مقاله «{{object}}» اطمینان دارید؟</p>
                  <input type="submit" name="" value="حذف" class="btn btn-danger">
              </form>
            </div>
</div>
{% endblock %}

accounts/templates/accounts/PostCrud/Ran.html
{{number}}