accounts/urls.py
from django.contrib.auth import views as viewsD
from django.urls import path
from . import views as viewsA


app_name= 'account'


urlpatterns = [
    path('', viewsA.PostList.as_view() ,name='panelHome'),
    path('Post/create/', viewsA.PostCreate.as_view() ,name='create'),
    path('Post/preview/<int:pk>', viewsA.PostPreview.as_view() ,name='preview'),
    path('Post/update/<int:pk>', viewsA.PostUpdate.as_view() ,name='update'),
    path('Category/create/', viewsA.CategoryCreate.as_view() ,name='create-category'),
    path('Post/delete/<int:pk>', viewsA.PostDelete.as_view() ,name='delete'),
    path('profile/', viewsA.Profile.as_view() ,name='profile'),
    path('Users/AuthorToUser/<int:pk>',viewsA.AuthorToUser.as_view(),name='AuthorToUser'),
    path('Users/situation/<int:pk>',viewsA.Situation.as_view(),name='situation'),
    path('Users/',viewsA.UserList.as_view(),name='userlist'),
    path('Post/Publish/<int:pk>', viewsA.PostPublish.as_view() ,name='publish'),
    path('َUsers/PasswordChangeView',viewsA.PasswordChangeView.as_view(),name='PasswordChangeView')

]

core/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('django.contrib.auth.urls')),
    path('', include('posts.urls')),
    path('panel/', include('accounts.urls')),
]



if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path,include
from . import views


app_name = "posts"
urlpatterns = [

    # Class views urls
    path('',views.PostListView.as_view(),name="home"),
    path('<int:page>/',views.PostListView.as_view(),name = "home"),
    path('posts/<slug>',views.PostDetail.as_view(),name = "post"),
    path('Authors/<slug:phoneNumber>',views.AuthorDetail.as_view(),name = "author"),
    path('Authors/<slug:phoneNumber>/<int:page>',views.AuthorDetail.as_view(),name = "author"),
    path('Category/<slug>',views.CategoryDetail.as_view(),name = "category"),
    path('Category/<slug>/<int:page>',views.CategoryDetail.as_view(),name = "category"),
    path('aboutUs/',views.aboutUsPage,name="aboutUs")
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, AbstractUser
from .managers import *
from django.utils import timezone
# ----------------------------------------------------------------------------------------------------------------------------
class User(AbstractBaseUser):
    phoneNumber = models.CharField(unique=True, max_length=11)
    firstName = models.CharField(max_length=100, null=True, blank=True)
    lastName = models.CharField(max_length=100, null=True, blank=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    special_user = models.DateTimeField(default=timezone.now, verbose_name="کاربر ویژه تا")
    Avatar = models.ImageField(upload_to="images/Avatar",blank=True,null=True)
    is_author = models.BooleanField(default = False, verbose_name = "وضعیت نویسندگی")

    code = models.IntegerField(blank=True,null=True)


    USERNAME_FIELD = 'phoneNumber'
    objects = MyUserManager()

    def __str__(self):
        return str(self.firstName) + " " + str(self.lastName)

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    def is_staff(self):
        return self.is_admin

    def name(self):
        return str(self.firstName) + " " + str(self.lastName)

    def is_special_user(self):
        if self.special_user > timezone.now():
            return True
        else:
            return False

    is_special_user.boolean = True
    is_special_user.short_description = "وضعیت کاربر ویژه"

accounts/forms.py
from django import forms
from .models import User
from posts.models import Post
from django.contrib.auth.forms import UserCreationForm


class ProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['phoneNumber','firstName','lastName','is_active','special_user','is_author']


    def __init__(self, *arg,**kwargs):
        user = kwargs.pop('user')

        super(ProfileForm, self).__init__( *arg,**kwargs)
        if not user.is_staff:
            self.fields['phoneNumber'].disabled = True
            self.fields['phoneNumber'].help_text = False
            self.fields['is_active'].disabled = True
            self.fields['special_user'].disabled = True
            self.fields['is_author'].disabled = True




class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=200)
    class Meta:
        model = User
        fields = ('phoneNumber', 'email', 'password1', 'password2')

accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from . import forms
from django.contrib.auth.views import LoginView
from django.views.generic import (
            ListView,
            CreateView,
            UpdateView,
            DeleteView,
            DetailView,)
from accounts.models import User
from posts import models
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import PasswordChangeView
from . import mixins

 # mixins.FormValidMixin,
#----------------------------------------------------------------------------------------------
class PostList(mixins.AuthorsAccessMixin,ListView):
    template_name = "accounts/adminlte/home.html"
    def get_queryset(self):
        if self.request.user.is_staff:
            return models.Post.objects.all()[::-1]
        else:
            return models.Post.objects.filter(Author=self.request.user)
#----------------------------------------------------------------------------------------------
class PostPreview(mixins.AuthorAccessMixin,DetailView):
    template_name = "posts/classBaseViews/Post_detail.html"
    def get_object(self):
        pk = self.kwargs.get('pk')
        return get_object_or_404(models.Post, pk=pk)
#----------------------------------------------------------------------------------------------
class PostUpdate(mixins.AuthorAccessMixin, mixins.FormValidMixin, mixins.FieldsMixin, UpdateView):
    template_name = "accounts/PostCrud/Post_create_update.html"
    model = models.Post
#----------------------------------------------------------------------------------------------
class PostDelete(mixins.SuperUserAccessMixin, mixins.FormValidMixin,DeleteView):
    template_name = "accounts/PostCrud/Post_delete.html"
    model = models.Post
    success_url = reverse_lazy('account:panelHome')
#----------------------------------------------------------------------------------------------
class PostCreate(mixins.FormValidMixin, mixins.FieldsMixin,mixins.AuthorsAccessMixin, CreateView):
    template_name = "accounts/PostCrud/Post_create_update.html"
    model = models.Post
    success_url = reverse_lazy('account:panelHome')

#----------------------------------------------------------------------------------------------
class Login(LoginView):
    def get_success_url(self):
        user = self.request.user

        if user.is_staff or user.is_author:
            return reverse_lazy('account:panelHome')
        else:
            return reverse_lazy('account:profile')
#----------------------------------------------------------------------------------------------
class CategoryCreate(mixins.AuthorsAccessMixin,mixins.FormValidCategoryMixin, CreateView):
    fields = ['title','Cover','slug','status']
    template_name = "accounts/PostCrud/Category_create_update.html"
    model = models.Category
    success_url = reverse_lazy('account:panelHome')
#----------------------------------------------------------------------------------------------
class Profile(LoginRequiredMixin, UpdateView):
    form_class = forms.ProfileForm
    template_name = "accounts/Profile.html"
    model = User
    success_url = reverse_lazy('account:panelHome')

    def get_object(self):
        return User.objects.get(pk=self.request.user.pk)

    def get_form_kwargs(self):
        kwargs = super(Profile, self).get_form_kwargs()
        kwargs.update({
            'user' : self.request.user
        })
        return kwargs
#----------------------------------------------------------------------------------------------
class PasswordChangeView(PasswordChangeView):
    success_url = reverse_lazy('account:password_change_done')
#----------------------------------------------------------------------------------------------
@login_required
def loginview(request):
    return render(request,'accounts/loginview.html')
#----------------------------------------------------------------------------------------------
class PostPublish(mixins.SuperUserAccessMixin, mixins.Form2ValidMixin,UpdateView):
    template_name = "accounts/PostCrud/Post_Publish.html"
    fields = ['status']
    model = models.Post
    success_url = reverse_lazy('account:panelHome')
#----------------------------------------------------------------------------------------------
class UserList(mixins.SuperUserAccessMixin,ListView):
    template_name = "accounts/User_list/User_list.html"
    def get_queryset(self):
        return User.objects.all()
#----------------------------------------------------------------------------------------------
class AuthorToUser(mixins.SuperUserAccessMixin, mixins.Form2ValidMixin,UpdateView):
    template_name = "accounts/User_list/User_situation.html"
    model = User
    fields = ['is_author']
    success_url = reverse_lazy('account:userlist')
#----------------------------------------------------------------------------------------------
class Situation(mixins.SuperUserAccessMixin,mixins.FieldsUserSituationMixin,mixins.Form3ValidMixin,UpdateView):
    template_name = "accounts/User_list/User_situation2.html"
    model = User
    success_url = reverse_lazy('account:userlist')
#----------------------------------------------------------------------------------------------

accounts/templates/accounts/adminlte/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>{% block titlemeta %}title{% endblock %}</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'accounts/adminlte/plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bbootstrap 4 -->
  <link rel="stylesheet" href="{% static 'accounts/adminlte/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'accounts/adminlte/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- JQVMap -->
  <link rel="stylesheet" href="{% static 'accounts/adminlte/plugins/jqvmap/jqvmap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'accounts/adminlte/dist/css/adminlte.min.css' %}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static 'accounts/adminlte/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{% static 'accounts/adminlte/plugins/daterangepicker/daterangepicker.css' %}">
  <!-- summernote -->
  <link rel="stylesheet" href="{% static 'accounts/adminlte/plugins/summernote/summernote-bs4.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
  <!-- Bootstrap 4 RTL -->
  <link rel="stylesheet" href="https://cdn.rtlcss.com/bootstrap/v4.2.1/css/bootstrap.min.css">
  <!-- Custom style for RTL -->
  <link rel="stylesheet" href="{% static 'accounts/adminlte/dist/css/custom.css' %}">
  <link rel="stylesheet" href="{% static 'mycustom.css' %}">
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'posts:home' %}" target="_blank" class="nav-link">صفحه ی اصلی</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'account:panelHome' %}" class="nav-link">خانه</a>
      </li>
    </ul>



  {% include 'accounts/adminlte/leftnavbar.html' %}

  </nav>
  <!-- /.navbar -->

  {% include 'accounts/adminlte/sidebar_blank.html' %}

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0 text-dark">{% block title %}عنوان{% endblock %}</h1>
          </div><!-- /.col -->

        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">


      {% block main %}{% endblock %}


        <!-- /.row (main row) -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <strong>پست ها</strong>
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{% static 'accounts/adminlte/plugins/jquery/jquery.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'accounts/adminlte/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 rtl -->
<script src="https://cdn.rtlcss.com/bootstrap/v4.2.1/js/bootstrap.min.js"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'accounts/adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- ChartJS -->
<script src="{% static 'accounts/adminlte/plugins/chart.js/Chart.min.js' %}"></script>
<!-- Sparkline -->
<script src="{% static 'accounts/adminlte/plugins/sparklines/sparkline.js' %}"></script>
<!-- JQVMap -->
<script src="{% static 'accounts/adminlte/plugins/jqvmap/jquery.vmap.min.js' %}"></script>
<script src="{% static 'accounts/adminlte/plugins/jqvmap/maps/jquery.vmap.world.js' %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static 'accounts/adminlte/plugins/jquery-knob/jquery.knob.min.js' %}"></script>
<!-- daterangepicker -->
<script src="{% static 'accounts/adminlte/plugins/moment/moment.min.js' %}"></script>
<script src="{% static 'accounts/adminlte/plugins/daterangepicker/daterangepicker.js' %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static 'accounts/adminlte/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
<!-- Summernote -->
<script src="{% static 'accounts/adminlte/plugins/summernote/summernote-bs4.min.js' %}"></script>
<!-- overlayScrollbars -->
<script src="{% static 'accounts/adminlte/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'accounts/adminlte/dist/js/adminlte.js' %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static 'accounts/adminlte/dist/js/pages/dashboard.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'accounts/adminlte/dist/js/demo.js' %}"></script>
</body>
</html>

accounts/templates/accounts/adminlte/home.html
{% extends 'accounts/adminlte/base.html' %}
{% load static %}
{% block titlemeta %}{% block title %}
  لیست پست ها
{% endblock %}{% endblock %}
{% block main %}<div class="row">
          <div class="col-12">
              {% if object_list %}
                  <div class="card">
                    <div class="card-header">
                      <h3 class="card-title">لیست پست</h3>

                      <div class="card-tools">
                        <div class="input-group input-group-sm" style="width: 150px;">
                          <input type="text" name="table_search" class="form-control float-right" placeholder="جستجو">

                          <div class="input-group-append">
                            <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
                          </div>
                        </div>
                      </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body table-responsive p-0">
                      <table class="table table-hover">
                        <thead>
                          <tr>
                            <th>شماره</th>
                            <th>تیتر</th>
                            <th>تصویر</th>
                            <th>نویسنده</th>
                            <th>متن</th>
                            <th>تاریخ انتشار</th>
                            <th>وضعیت</th>
                          </tr>
                        </thead>
                        <tbody>
                          {% for post in object_list %}
                          <tr>
                            <td>{{post.id}}</td>
                            {% if post.status in 'db'|make_list or user.is_staff %}
                            <td><a href="{% url 'account:update' post.pk %}">{{post.title}}</a></td>
                            {% else %}
                            <td>{{post.title}}</td>
                            {% endif %}
                            <td><img src="{{post.Cover.url}}" width="90"></td>
                            <td>{{post.Author}}</td>
                            <td>{{post.preview|safe}}</td>
                            <td>{{post.jpublish}}</td>
                            <td>
                              {% if post.status == 'p' %}
                              <span class="badge badge-success">منتشر شده</span>
                              <a target="_blank" href="{% url 'posts:post' post.slug %}" class="badge badge-primary">صفحه </a>
                              {% elif post.status == 'i' %}
                              <span class="badge badge-primary" style="background-color: #777474;">در حال بررسی</span>
                              {% else %}
                                {% if post.status == 'd' %}
                                    <span class="badge badge-danger">پیش نویس</span>
                                    <a target="_blank" href="{% url 'account:preview' post.pk %}" class="badge badge-primary" >پیش نمایش</a>
                                {% elif post.status == 'b' %}
                                    <span class="badge badge-danger"style="background-color: #8a7c00;">برگشت داده شده</span>
                                    <a target="_blank" href="{% url 'account:preview' post.pk %}" class="badge badge-primary" >پیش نمایش</a>
                                {% endif %}
                              {% endif %}
                              {% if user.is_staff %}
                                <a href="{% url 'account:delete' post.pk %}" class="badge badge-danger">حذف</a>
                                <a href="{% url 'account:publish' post.pk %}" class="badge badge-danger" style="background-color: #0031a0;">تغییر وضعیت انتشار</a>
                          {% endif %}
                        </td>
                      </tr>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
                <!-- /.card-body -->
              </div>

              {% else %}
                <h3>محتوایی برای نمایش وجود ندارد.</h3>
              {% endif %}
          </div>
        </div>
{% endblock %}

accounts/templates/accounts/adminlte/leftnavbar.html
{% load static %}
<ul class="navbar-nav mr-auto-navbav">
  <!-- Notifications Dropdown Menu -->
  <li class="nav-item">
    <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="{% url 'logout' %}">
      <i class="fas fa-sign-out-alt"></i>
    </a>
  </li>
</ul>

accounts/templates/accounts/adminlte/sidebar_blank.html
{% load static %}
{% load base_tags %}
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
  <a href="index3.html" class="brand-link">
    <img src="{% static 'accounts/adminlte/dist/img/AdminLTELogo.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
         style="opacity: .8">
    <span class="brand-text font-weight-light">{% block title1 %}پنل{% endblock %}</span>
  </a>

  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
        <img src="{% if user.Avatar %}{{user.Avatar.url}}{% else %}{% static 'posts/images/yoy.jpg' %}{% endif %}" class="img-circle elevation-2" alt="User Image">
      </div>
      <div class="info">
        <a href="#" class="d-block ">{{user}}</a>
      </div>
    </div>

    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
             with font-awesome or any other icon font library -->
        <li class="nav-item has-treeview menu-open">
          <a href="#" class="nav-link active">
            <i class="nav-icon fas fa-tachometer-alt"></i>
            <p>
            داشبورد
              <i class="right fas fa-angle-left"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            {% if user.is_staff or user.is_author %}
              <li class="nav-item">
                {% link request 'panelHome' 'لیست مقالات'  'fa fa-list nav-icon' %}
              </li>
              <li class="nav-item">
                {% link request 'create' 'افزودن مقاله' 'fa fa-edit nav-icon' %}
              </li>
                {% if user.is_staff %}
                <li class="nav-item">
                    {% link request 'create-category' 'افزودن دسته بندی' 'fa fa-edit nav-icon' %}
                </li>
                <li class="nav-item">
                    {% link request 'userlist' 'لیست کاربرها' 'fa fa-glasses nav-icon' %}
                </li>
                <li class="nav-item">
                    {% link request 'PasswordChangeView' 'عوض کردن رمز عبور' 'fa fa-glasses nav-icon' %}
                </li>
                {% endif %}
              {% endif %}
              <li class="nav-item">
              {% link request 'profile' 'پروفایل' 'fa fa-th nav-icon' %}
              </li>

          </li>
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>